import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import { unified } from "unified";
import { visit } from "unist-util-visit";
import type { AnimationLanguage } from "./animationChecks";
import { resolveAnimationLanguage } from "./animationChecks";

export const WRYTE_MANAGED_MARKER = "wryte:managed";

export type AnimationSourceMap = Record<string, string>;

export type TransformedComponent = {
  name: string;
  repoPath: string;
  fileContent: string;
};

export type AnimationTransformResult = {
  body: string;
  components: TransformedComponent[];
};

type MdxJsxNode = {
  type: string;
  name?: string | null;
  attributes?: { type: string; name?: string }[];
  position?: {
    start: { offset?: number };
    end: { offset?: number };
  };
};

function normalizePath(p: string): string {
  return p.replace(/^\/+|\/+$/g, "").replace(/\/{2,}/g, "/");
}

export function relativeImportDir(
  contentDir: string,
  animationsDir: string,
): string {
  const from = normalizePath(contentDir).split("/").filter(Boolean);
  const to = normalizePath(animationsDir).split("/").filter(Boolean);
  let common = 0;
  while (common < from.length && common < to.length) {
    if (from[common] !== to[common]) break;
    common++;
  }
  const ups = from.length - common;
  const downs = to.slice(common);
  const segments = [...Array<string>(ups).fill(".."), ...downs];
  if (segments.length === 0) return ".";
  const joined = segments.join("/");
  return joined.startsWith(".") ? joined : `./${joined}`;
}

function managedHeader(name: string): string {
  return `/* ${WRYTE_MANAGED_MARKER} — "${name}" animation generated by Wryte.\n * Edits to this file are overwritten on the next publish; edit the\n * animation inside Wryte instead. */\n`;
}

export function transformMdxWithAnimations(
  body: string,
  animations: AnimationSourceMap,
  opts: {
    framework?: string | undefined;
    contentDir: string;
    animationsDir: string;
    language?: AnimationLanguage | string | undefined;
  },
): AnimationTransformResult {
  const known = new Set(Object.keys(animations));
  if (known.size === 0) return { body, components: [] };

  const tree = unified().use(remarkParse).use(remarkMdx).parse(body);

  const referenced = new Set<string>();
  const spliceOffsets: number[] = [];

  const collect = (node: MdxJsxNode) => {
    if (!node.name || !known.has(node.name)) return;
    referenced.add(node.name);

    if (opts.framework === "astro") {
      const hasDirective = (node.attributes ?? []).some(
        (a) =>
          a.type === "mdxJsxAttribute" && (a.name ?? "").startsWith("client:"),
      );
      const end = node.position?.end.offset;
      if (!hasDirective && typeof end === "number") {
        if (body.slice(end - 2, end) === "/>") {
          spliceOffsets.push(end - 2);
        }
      }
    }
  };

  visit(tree, "mdxJsxFlowElement", (n) => collect(n as MdxJsxNode));
  visit(tree, "mdxJsxTextElement", (n) => collect(n as MdxJsxNode));

  if (referenced.size === 0) return { body, components: [] };

  let rewritten = body;
  for (const offset of spliceOffsets.sort((a, b) => b - a)) {
    rewritten = `${rewritten.slice(0, offset)}client:visible ${rewritten.slice(offset)}`;
  }

  const importDir = relativeImportDir(opts.contentDir, opts.animationsDir);
  const names = [...referenced].sort();
  const imports = names
    .map((n) => `import ${n} from "${importDir}/${n}";`)
    .join("\n");
  rewritten = `${imports}\n\n${rewritten}`;

  const useClient = opts.framework === "nextjs" ? `"use client";\n\n` : "";
  const ext = resolveAnimationLanguage(opts.language);
  const components: TransformedComponent[] = names.map((name) => ({
    name,
    repoPath: `${normalizePath(opts.animationsDir)}/${name}.${ext}`,
    fileContent: `${managedHeader(name)}${useClient}${animations[name] ?? ""}`,
  }));

  return { body: rewritten, components };
}
