/**
 * Publish-time transform for code animations.
 *
 * Takes the raw MDX body the author wrote (plain `<Anim />` tags, no imports,
 * no framework directives) and produces:
 *  - the rewritten body: import lines prepended, `client:visible` injected on
 *    Astro targets;
 *  - the list of referenced components with their target repo paths and
 *    final .tsx file contents (marker header + optional "use client").
 *
 * Parsing uses remark + remark-mdx so a `<Anim />` inside a code fence or
 * inline code can never be mistaken for a real reference. Rewriting does NOT
 * re-serialize the AST — remark-stringify would reformat the author's entire
 * document (bullet styles, emphasis markers, wrapping). Instead the AST is
 * used only to *locate* real JSX nodes, and edits are applied as offset-based
 * string splices, so every byte the author wrote stays exactly as written.
 */

import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import { unified } from "unified";
import { visit } from "unist-util-visit";
import type { AnimationLanguage } from "./animationChecks";
import { resolveAnimationLanguage } from "./animationChecks";

/** Marker embedded in every generated .tsx. Publish refuses to overwrite a
 * file at the target path that lacks it — never clobber hand-written code. */
export const WRYTE_MANAGED_MARKER = "wryte:managed";

export type AnimationSourceMap = Record<string, string>;

export type TransformedComponent = {
  name: string;
  /** Repo path of the component file, e.g. "src/components/blog/HarnessLoop.tsx" */
  repoPath: string;
  /** Final file contents: marker header (+ "use client" for Next) + source */
  fileContent: string;
};

export type AnimationTransformResult = {
  body: string;
  components: TransformedComponent[];
};

type MdxJsxNode = {
  type: string;
  name?: string | null;
  attributes?: { type: string; name?: string }[];
  position?: {
    start: { offset?: number };
    end: { offset?: number };
  };
};

/** Normalize a repo path: strip leading/trailing slashes, collapse doubles. */
function normalizePath(p: string): string {
  return p.replace(/^\/+|\/+$/g, "").replace(/\/{2,}/g, "/");
}

/**
 * Relative import path from the directory containing the post to the
 * animations directory — pure POSIX segment math (repo paths, never OS
 * paths). E.g. "src/content/blog" → "src/components/blog" yields
 * "../../components/blog".
 */
export function relativeImportDir(
  contentDir: string,
  animationsDir: string,
): string {
  const from = normalizePath(contentDir).split("/").filter(Boolean);
  const to = normalizePath(animationsDir).split("/").filter(Boolean);
  let common = 0;
  while (common < from.length && common < to.length) {
    if (from[common] !== to[common]) break;
    common++;
  }
  const ups = from.length - common;
  const downs = to.slice(common);
  const segments = [...Array<string>(ups).fill(".."), ...downs];
  if (segments.length === 0) return ".";
  const joined = segments.join("/");
  return joined.startsWith(".") ? joined : `./${joined}`;
}

/** Header comment for generated files — carries the managed marker. */
function managedHeader(name: string): string {
  return `/* ${WRYTE_MANAGED_MARKER} — "${name}" animation generated by Wryte.\n * Edits to this file are overwritten on the next publish; edit the\n * animation inside Wryte instead. */\n`;
}

/**
 * Transform an MDX body for publish.
 *
 * @param body           Raw MDX body (no frontmatter).
 * @param animations     name → TSX source for every animation in the project.
 * @param opts.framework Project framework ("astro" | "nextjs" | other).
 * @param opts.contentDir     Repo dir containing the post file.
 * @param opts.animationsDir  Repo dir receiving the .tsx files.
 */
export function transformMdxWithAnimations(
  body: string,
  animations: AnimationSourceMap,
  opts: {
    framework?: string | undefined;
    contentDir: string;
    animationsDir: string;
    /** Absent = "tsx". Decides the extension the component is written as. */
    language?: AnimationLanguage | string | undefined;
  },
): AnimationTransformResult {
  const known = new Set(Object.keys(animations));
  if (known.size === 0) return { body, components: [] };

  const tree = unified().use(remarkParse).use(remarkMdx).parse(body);

  const referenced = new Set<string>();
  /** " client:visible" insertions, as offsets into the original body. */
  const spliceOffsets: number[] = [];

  const collect = (node: MdxJsxNode) => {
    if (!node.name || !known.has(node.name)) return;
    referenced.add(node.name);

    if (opts.framework === "astro") {
      // Only annotate when the author hasn't hand-written a client: directive.
      const hasDirective = (node.attributes ?? []).some(
        (a) =>
          a.type === "mdxJsxAttribute" && (a.name ?? "").startsWith("client:"),
      );
      const end = node.position?.end.offset;
      if (!hasDirective && typeof end === "number") {
        // ponytail: only self-closing tags (`<Anim />`) get the directive —
        // that's the only form the editor inserts. A hand-written paired tag
        // (`<Anim>…</Anim>`) publishes without hydration; extend to locate
        // the opening tag's end if authors ever write those.
        if (body.slice(end - 2, end) === "/>") {
          spliceOffsets.push(end - 2);
        }
      }
    }
  };

  visit(tree, "mdxJsxFlowElement", (n) => collect(n as MdxJsxNode));
  visit(tree, "mdxJsxTextElement", (n) => collect(n as MdxJsxNode));

  if (referenced.size === 0) return { body, components: [] };

  // Apply directive splices right-to-left so earlier offsets stay valid.
  let rewritten = body;
  for (const offset of spliceOffsets.sort((a, b) => b - a)) {
    rewritten = `${rewritten.slice(0, offset)}client:visible ${rewritten.slice(offset)}`;
  }

  // Prepend one import per referenced component. MDX treats top-level import
  // statements as ESM — Astro and @next/mdx compile them at build time.
  const importDir = relativeImportDir(opts.contentDir, opts.animationsDir);
  const names = [...referenced].sort();
  const imports = names
    .map((n) => `import ${n} from "${importDir}/${n}";`)
    .join("\n");
  rewritten = `${imports}\n\n${rewritten}`;

  const useClient = opts.framework === "nextjs" ? `"use client";\n\n` : "";
  const ext = resolveAnimationLanguage(opts.language);
  const components: TransformedComponent[] = names.map((name) => ({
    name,
    repoPath: `${normalizePath(opts.animationsDir)}/${name}.${ext}`,
    fileContent: `${managedHeader(name)}${useClient}${animations[name] ?? ""}`,
  }));

  return { body: rewritten, components };
}
