export const editorLines = [
  "---",
  'title: "Shipping Faster with Wryte"',
  "date: 2026-04-07",
  "tags: [devtools, workflow]",
  "draft: false",
  "---",
  "",
  "# The Developer Content Problem",
  "",
  "Most developers write in markdown but",
  "publishing still means committing,",
  "pushing, and waiting for deploys.",
  "",
  "**Wryte changes that.** One click from",
  "editor to your GitHub-powered site.",
];

export const marqueeItems = [
  "Markdown Editor",
  "Kanban Board",
  "GitHub Publishing",
  "Live Preview",
  "Drag & Drop",
  "Auto-Save",
  "Scheduling",
  "Keyboard Shortcuts",
  "Smart Frontmatter",
  "Inline Editing",
  "Multi-Select",
  "Dark Mode",
  "AI Polish",
  "Open Source",
];
